### ISSUE TITLE
Netsaur support (perhaps)

### ISSUE THREAD

**Issue by load1n9** [sauber/deno-dashboard#1]

**Comment by sauber** [comment]
Thanks for support request.

The dashboard doesn't currently "support" any specific backends. Instead the user is required to write callback glue functions to bridge the systems.

One function is for the training loop to periodically call the dashboard.

The other function is for the dashboard to extract predictions from the neural network.

Two examples are already included and it would be a good idea to add an example for Netsaur. 

I see some challenges.

1) Netsaur doesn’t support periodic callbacks during training. A workaround could be for the bridging function to alternate between running small training batches and displaying dashboard.

2) Netsaur’s predict() function returns a promise instead of results. A workaround could be to pre-supply the full scatterplot dataset to the dashboard instead of a callback function to pull out the data on demand.

Would you like to create and link a pull request?

**Comment by sauber** [comment]
I have created an outline of how integration with Netsaur in example file in branch netsaur:

https://github.com/sauber/deno-dashboard/blob/netsaur.ts/examples/netsaur.ts

There are two issues:

1) I don't know how to pull out error or loss from most recent training cycle.
2) The code fails with this message:

```bash
> deno run examples/netsaur.ts
✅ Granted all env access.
✅ Granted all read access.
WASM Backend Initialized
WASM Backend Initialized
error: Uncaught (in promise) RuntimeError: unreachable
    at <anonymous> (file://AppData/Local/deno-wasmbuild/42c55b3172f1872961a9685a84daf6e54e735a52f07000cff904dc40dc0e8097.wasm:1:980339)
    at <anonymous> (file://AppData/Local/deno-wasmbuild/42c55b3172f1872961a9685a84daf6e54e735a52f07000cff904dc40dc0e8097.wasm:1:994082)
    at <anonymous> (file://AppData/Local/deno-wasmbuild/42c55b3172f1872961a9685a84daf6e54e735a52f07000cff904dc40dc0e8097.wasm:1:953005)
    at <anonymous> (file://AppData/Local/deno-wasmbuild/42c55b3172f1872961a9685a84daf6e54e735a52f07000cff904dc40dc0e8097.wasm:1:296393)
    at <anonymous> (file://AppData/Local/deno-wasmbuild/42c55b3172f1872961a9685a84daf6e54e735a52f07000cff904dc40dc0e8097.wasm:1:367058)
    at wasm_backend_train (https://jsr.io/@denosaurs/netsaur/0.4.2/packages/core/src/backends/wasm/lib/netsaur.generated.js:171:8)
    at WASMBackend.train (https://jsr.io/@denosaurs/netsaur/0.4.2/packages/core/src/backends/wasm/backend.ts:53:5)
    at Sequential.train (https://jsr.io/@denosaurs/netsaur/0.4.2/packages/core/src/core/mod.ts:41:18)
    at file://examples/netsaur.ts:78:7
    at eventLoopTick (ext:core/01_core.js:175:7)
```
